//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Pages.Employee {
    
    
    public partial class EditEmployee {
        
        /// <summary>
        /// employeeDropDown control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BusinessLogic.Components.EmployeeDropDown employeeDropDown;
        
        /// <summary>
        /// editEmployeeControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Web.Controls.EditEmployeeControl editEmployeeControl;
        
        /// <summary>
        /// editUpdateCancelControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Web.Controls.EditUpdateSaveCancelControl editUpdateCancelControl;
    }
}
